New introductory blog post (series)
kolabri/kolabri.io pull request #10
Opened 2024-03-12 13:22 UTC by michaeldorner

Based on our IEEE Software article, I wrote the first blog post on a series of three blog posts for our start page. 

Feel free to fix issues yourself or let me know what you think.

2024-03-12 17:43 UTC, maxcapraro requested changes
Vielen lieben Dank für die beiden Blog Posts @michaeldorner. Meiner Meinung nach treffen sie exakt die richtige Balance zwischen Qualität (gute Blog-Posts!) und Geschwindigkeit (wir wollen sie zeitnah auf der Website verlinken können!) 👍 Hut ab 🎩 

Ich habe zwar viele Kommentare hinterlassen, die sind aber zum Großteil editorischer Natur. Wo möglich, habe ich direkt konkrete Änderungsvorschläge hinzugefügt.

Nochmal vielen Dank und großes Lob für die Arbeit ❤️

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +slug: 'what-is-it-all-about'
Die URL mit dem Slug zu modifizieren hat imho zwei Ziele: Die URL für Menschen gefälliger/lesbarer zu machen sowie SEO. Für SEO finde ich diesen Slug nicht optimal (für Menschen dafür prima!).

Um beides unter einen Hut zu bringen wäre mein Vorschlag entweder gar keinen manuellen Slug zu vergeben (lesbar, aber lang) oder alternativ einen SEO-freundlicheren Slug mit mehr Kontext zu wählen:

```suggestion
slug: 'tax-compliance-in-software-engineering-fundamental-challenges'
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +slug: 'what-is-it-all-about'
⚠️ Bitte links nicht vergessen 🙂

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +title: 'Tax Compliance for Software Engineering: The Fundemental Challenges in Software Engineering'
```suggestion
title: 'Tax Compliance for Software Engineering: The Fundemental Challenges'
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +# Tax Compliance for Software Engineering: The Fundemental Challenges in Software Engineering
```suggestion
# Tax Compliance for Software Engineering: The Fundemental Challenges
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +date: 2024-03-12T06:00:00+02:00
Um mehr Leben im Blog zu erzeugen (vorzutäuschen?) und die Reihenfolge expliziter zu kennzeichnen, würde ich diesen Blog-Post eine Woche nach dem anderen erscheinen lassen:

```suggestion
date: 2024-03-19T06:00:00+02:00
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +slug: 'what-is-it-all-about'
Huch 😸 Du hast hier die gleiche URL vergeben, wie oben. Wie wäre es mit:
```suggestion
slug: 'tax-compliance-in-software-engineering-foundations'
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +title: 'Tax Compliance for Software Engineering: What Is It All About?'
"What is it all about?" finde ich irgendwie zu schwach (und ich bin mir bewusst, dass ich das schreibe, als jemand, der heute eine Wiki-Seite mit dem Titel "Use? What's so difficult?" angelegt hat).
Wie wäre es mit?
- Tax Compliance for Software Engineering: Foundations
- Tax Compliance for Software Engineering: Introduction
- Tax Compliance for Software Engineering: The Problem*

*) Dann könnten wir im zweiten Artikel aber nicht mehr `The Fundamental Challenges` schreiben, weil die Abgrenzung nicht klar ist und müssten dort eher sowas wählen wie `Three Dimensions of the Solution` oder `Three Nuts to Crack`.

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +## A simplified example
Kannst du bitte konsistent die Überschriften im [title case / headline case](https://en.wikipedia.org/wiki/Title_case) machen?

Falls es dir zu zeitaufwändig ist, lass es mich bitte hier per Kommentar wissen und ich stelle es dann form Merge um. Falls etwas dagegen spricht, lass es mich natürlich bitte auch hier wissen.

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +Modern software systems are often too large, too complex, and evolving too fast for single developers to oversee. Therefore, software engineering has become highly collaborative. Often, engineers and
Die Dopplung der Wortgruppe "collaborate accross borders" würde ich entfernen:

```suggestion
Modern software systems are often too large, too complex, and evolving too fast for single developers to oversee. Therefore, software engineering has become highly collaborative. Often, engineers and their teams collaborate across borders, especially in multinational companies with subsidiaries spread around the globe. Such collaboration has an often overlooked legal implication: the profits from those cross-border collaborations become taxable.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +In this first blog post in our series on tax compliance for software engineering, we start with a gentle introduction to international standards in multinational taxation and its basic arm's length p
```suggestion
In this first blog post in our series on tax compliance for software engineering, we start with a gentle introduction to international standards in multinational taxation and its basic Arm's Length Principle from a software engineering perspective. And no worries, no prior knowledge or background is needed. In future blog posts of this series, we will then discuss the unique challenges of taxing collaborative software engineering and illustrate the industrial significance of cross-border collaboration using code review in a large software company as example.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +Now that we understand the underlying mechanics of tax compliance and the transfer price at *arm's length* as its guiding principle, read our [next blog post, where we discuss the tax compliance chal
```suggestion
Now that we understand the underlying mechanics of tax compliance and the transfer price at *arm's length* as its guiding principle, read the [next blog post in this series, where we discuss the tax compliance challenges specific to software engineering](/content/blog/2024-challenges/_index.md).
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +Let's start with a fictitious multinational enterprise called *devnullsoft Group* that develops and sells a software-intensive product. *devnullsoft Group* has two legal entities: *devnullsoft GmbH*
```suggestion
Let's start with a fictitious multinational enterprise called *devnullsoft Group* that develops and sells a software-intensive product. *devnullsoft Group* has two legal entities: *devnullsoft GmbH* in Germany and its subsidiary *devnullsoft AB* in Sweden. The German development team employed by *devnullsoft GmbH* develops software jointly with their Swedish colleagues employed by *devnullsoft AB*. The German *devnullsoft GmbH* sells the resulting product to customers.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +To avoid this scenario and to provide a common ground for international taxation, reducing uncertainty for multinational enterprises, and preventing tax avoidance through profit shifting, nearly all
```suggestion
To avoid this scenario and to provide a common ground for international taxation, reducing uncertainty for multinational enterprises, and preventing tax avoidance through profit shifting, nearly all countries in the world agreed on and implemented the so-called Arm's Length Principle as defined in the [OECD Transfer Pricing Guidelines for Multinational Enterprises and Tax Administrations](https://www.oecd.org/tax/transfer-pricing/oecd-transfer-pricing-guidelines-for-multinational-enterprises-and-tax-administrations-20769717.htm). The arm's length principle is the guiding principle and the de-facto standard for the taxation of multinational enterprises. It requires associated enterprises to operate as if they were not associated to one another or - in other words - regular participants in a free market. This principle ensures that transfer prices between associated companies of multinational enterprises are established on a market value basis and not misused for profit shifts from high to low tax regions.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +To avoid this scenario and to provide a common ground for international taxation, reducing uncertainty for multinational enterprises, and preventing tax avoidance through profit shifting, nearly all
Müssen wir "associated enterprise" definieren? Da es ein Blog Post ist könnten wir vmtl. drauf verzichten.

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +In the schematic overview above, we summarize the mechanics of our fictitious company of transfer pricing between the two associated software companies from our example. Although *devnullsoft AB* con
```suggestion
In the schematic overview above, we summarize the mechanics of our fictitious company of transfer pricing between the two associated software companies from our example. Although *devnullsoft AB* contributed significantly to the software-intensive product, without a transfer price, *devnullsoft AB* has no share of profits; all profits are fully taxable in Germany only. Thus, it violates the Arm's Length Principle. However, if *devnullsoft GmbH* in Germany pays a transfer price reflecting the value for the services and intangible properties received from its Swedish associated enterprise, *devnullsoft AB* realizes profits, which then are taxable in Sweden. The Arm's Length Principle is upheld.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +The *devnullsoft Group* does not artificially shift profits to a tax haven. Yet, one can easily imagine that neglecting to charge arm's length prices can be intentionally misused for profit-shifting.
Fällt dir eine drastischere alarmigere Formulierung hierfür ein?

> From the companies' perspective, its software development may be (intentionally or unintentionally) non-compliant and face the risk of being legally prosecuted.

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +In this second blog post in our [series on tax compliance for software engineering](/content/blog/2024-what-is-it-all-about/_index.md), we will discuss the unique and fundamental challenges of taxing
👍 Sehr clever mit dem Eingangs-Paragraphen der immer gleich bleibt und anschließend der Überleitung, zur Blog-Post-Serie.

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-what-is-it-all-about/_index.md
> +Modern software systems are often too large, too complex, and evolving too fast for single developers to oversee. Therefore, software engineering has become highly collaborative. Often, engineers and
(Änderung, falls akzeptabel, im zweiten Blog-Post nicht vergessen)

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +So, what are transfer prices for collaborative software engineering that comply with this arm's length principle? Determining a market price for intangibles is inherently difficult and is reflected i
Klar, wir haben im letzten Blog-Post das `Arm's Length Principle` erklärt. Wir wissen aber nicht, wie die Leute auf diesen (den zweiten) Blog-Post aufmerksam geworden sind. Deshalb würde ich wohl noch einen Erklärsatz hinzufügen:

```suggestion
Associated enterprises are required to behave and charge each other as if they were independent third parties - the so called Arm's Length Principle. So, what are transfer prices for typical transactions in collaborative software engineering that comply with this principle? Determining a market price for intangibles is inherently difficult and is reflected in a broad price range. Collaborative software engineering, however, scales the problem of a transfer-price determination to a new level of complexity because the reality of modern software engineering is significantly more complex than our introductory example above may suggest. Since transfer price regulations apply to a much broader definition of intangibles compared to accounting standards, the latter can not be used as a reliable measure of value for transfer pricing purposes.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +From our last [blog post](/content/blog/2024-what-is-it-all-about/_index.md), we understood that companies must pay a transfer price for goods, intangibles, or services transferred in a multinational
Der Paragraph scheint mir irgendwie eine Dopplung zum vorherigen (der allerdings schon einen Verweis auf den letzten Blog-Post enthält). Kann einer der beiden Paragraphen entfallen?

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +In the following, we discuss three main high-level challenges for transfer pricing in collaborative software engineering within multinational enterprises. The figure below highlights the complexity i
```suggestion
There are three high-level challenges for transfer pricing in collaborative software engineering within multinational enterprises. The figure below illustrates the complexity in modern collaborative software engineering at *devnullsoft Group* (the fictitious multinational company introduced in [the previous post of this series](/content/blog/2024-what-is-it-all-about/_index.md)) and where those three challenges apply.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +The trouble for transfer pricing in software engineering begins with a fundamental question: What is actually a taxable transaction in the context of collaborative software engineering? We simply do
```suggestion
The trouble for transfer pricing in software engineering begins with a fundamental question: What is actually a taxable transaction in the context of collaborative software engineering? It is not immediately clear what types or characteristics classify a taxable exchange of intangibles or services across the boundaries of a country in the context of software engineering.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +Among other potentially relevant types of taxable intangibles, such as *goodwill* or *group synergies*, we discuss in this and the following subsections two types of intangibles that are highly relev
```suggestion
Among other potentially relevant types of taxable intangibles, such as *goodwill* or *group synergies*, this blog post focusses on two types of intangibles that are highly relevant for software engineering: *know-how* and *licenses*.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +Additionally, we see an interplay between those two types of intangibles, know-how and licensing, since they may be two sides of the same collaboration. For example, when code contributions from the
```suggestion
Additionally, we see an interplay between those two types of intangibles, know-how and licensing, since they may be two sides of the same collaboration. For example, when code contributions from a component user support instances of reuse.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +While it is inherently difficult to tax intangibles in general, things are even more complicated in software engineering. Potentially taxable intangibles cover a large range of granularity in softwar
```suggestion
While it is inherently difficult to tax intangibles in general, things are even more complicated in software engineering. Potentially taxable intangibles cover a large range of granularity: They may be as large as a microservice providing user authentication which itself is used by microservices of other teams (see intangible *licenses*) or as small as a code change, code review, or bug report (see intangible *know-how*). Although the code change or feedback in a code review is small - maybe even only one line of code, like in the case of the *Heartbleed* security bug in the OpenSSL cryptography library from 2014-the potential impact on the software system can be tremendous or even fatal. A software change or a code review delivers value through impact, not size.
```

2024-03-12 17:43 UTC, maxcapraro commented on content/blog/2024-challenges/index.md
> +If you want to learn more about how we at Kolabri addresses those challenges, read our brochure on how we leverage data analytics for tax compliance in software engineering. If you want to learn more
```suggestion
If you want to learn more about how we at Kolabri address those challenges, read our brochure on data analytics for tax compliance in software engineering. If you want to learn more about the prevalence of cross-border collaboration in modern collaborative software engineering and how we measured it, stay tuned for the next blog post in our series on tax compliance for software engineering.
```

2024-03-13 06:38 UTC, michaeldorner commented on content/blog/2024-challenges/index.md
> +slug: 'what-is-it-all-about'
Wir können gerne einen längeren slug nehmen, aber challenges ist der zweite blog post. :) Ich würde also `tax-compliance-in-software-engineering-what-is-it-all-about` nehmen

2024-03-13 06:40 UTC, merged